services:
- name: ${{ env "DECK_SERVICE_TAG" }}-service
  enabled: true
  url: https://httpbin
  routes:
  - name: ${{ env "DECK_SERVICE_TAG" }}-test-route
    paths:
      - /bin
  - name: ${{ env "DECK_SERVICE_TAG" }}-key-auth-route
    paths:
      - /key