services:
- enabled: true
  host: 127.0.0.1
  name: ${{ env "DECK_SERVICE_TAG" }}-dummy-service
  port: 65535
  protocol: https
  routes:
  - name: ${{ env "DECK_SERVICE_TAG" }}-route
    paths:
      - /